-- Enable RLS for public tables (security hardening)

ALTER TABLE IF EXISTS public.login_security ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.staff_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.inventory_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.inventory_check_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.email_verification_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.audit_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.taikhoan ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.nhanvien ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.khachhang ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.nhacc ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.loaihang ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hanghoa ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.phieunhap ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ctphieunhap ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.phieuxuat ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ctphieuxuat ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hoadon ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ct_hoadon ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.dovi_vanchuyen ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hinhanh_hanghoa ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.legal_documents ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public."EInvoiceLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."InvoiceSeries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."DieuKhoanPhapLy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."LuatQuyDinh" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."YeuCau" ENABLE ROW LEVEL SECURITY;

SELECT '✅ Enabled RLS where tables exist' AS status;
